### ISSUE TITLE
Improvements 1

### ISSUE THREAD

**Issue by S4NDW1CH** [DYN-IT-EDU/d.korobkina-i.sobolev_movie-studio#1]
Если используется логгинг, то рекомендуется создавать отдельные логгеры для каждого модуля (файла) с помощью `const LOG = cds.log('название модуля')`.
[Советую ознакомиться.](https://cap.cloud.sap/docs/node.js/cds-log)

Цифровые литералы по возможности следует заменять на константы и енамы, отображающие их смысл. `status = OrderStatus.CLOSED` гораздо понятнее, чем `status = 102`.
[enum в cds](https://cap.cloud.sap/docs/cds/cdl#enums)

**Comment by Sobolevigor7** [comment]
Логгинг поправил согласно замечаний. Список статусов теперь - читаемые статусы (enum), в тестовых данных для деплоя в HANA - тоже данные исправил.
